//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.HotelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/HotelService")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarRatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StarRating {
            get {
                return this.StarRatingField;
            }
            set {
                if ((object.ReferenceEquals(this.StarRatingField, value) != true)) {
                    this.StarRatingField = value;
                    this.RaisePropertyChanged("StarRating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelServiceReference.IHotelOperations")]
    public interface IHotelOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetAllHotels", ReplyAction="http://tempuri.org/IHotelOperations/GetAllHotelsResponse")]
        Client.HotelServiceReference.Hotel[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetAllHotels", ReplyAction="http://tempuri.org/IHotelOperations/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<Client.HotelServiceReference.Hotel[]> GetAllHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetHotelById", ReplyAction="http://tempuri.org/IHotelOperations/GetHotelByIdResponse")]
        Client.HotelServiceReference.Hotel GetHotelById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetHotelById", ReplyAction="http://tempuri.org/IHotelOperations/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<Client.HotelServiceReference.Hotel> GetHotelByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelOperationsChannel : Client.HotelServiceReference.IHotelOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelOperationsClient : System.ServiceModel.ClientBase<Client.HotelServiceReference.IHotelOperations>, Client.HotelServiceReference.IHotelOperations {
        
        public HotelOperationsClient() {
        }
        
        public HotelOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.HotelServiceReference.Hotel[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<Client.HotelServiceReference.Hotel[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
        
        public Client.HotelServiceReference.Hotel GetHotelById(int id) {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<Client.HotelServiceReference.Hotel> GetHotelByIdAsync(int id) {
            return base.Channel.GetHotelByIdAsync(id);
        }
    }
}
